# Tutorial 1 - NumPy

### Python Arrays

In [1]:
# Python list is basically an array
x = [1,2,3,4]
y = [5,6,7,8]
# Let's print x + y
print('First print output:', x+y)
# Let's print x*2
print('Second print output:',x*2)

First print output: [1, 2, 3, 4, 5, 6, 7, 8]
Second print output: [1, 2, 3, 4, 1, 2, 3, 4]


In [2]:
# You can't do the following with Python lists
x + 10

TypeError: can only concatenate list (not "int") to list

### Numpy
Numpy is a Python module (a library) that adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays in Python. Using NumPy in Python gives functionality comparable to MATLAB since they are both interpreted, and they both allow the user to write fast programs as long as most operations work on arrays or
matrices instead of scalars.

For Matlab users please also see the following:
https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html

In [3]:
# This is how you import a module.
# np is used to shorten the name
# Use module_name.function_name() to call specific NumPy methods in code
import numpy as np

In Python, the `import` statement creates a binding (a place in memory) for module `np`. To call functions that are defined in the module `np` we most use the "dot notation." Below, we create a NumPy array `x` by calling

`x = np.array([your list])`

In [13]:
# Let's assign arrays  to variables x,y using NumPy
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
# Let's show the result of x
x

array([1, 2, 3, 4])

In [17]:
# This perfroms element-wise addition
x + 10

array([11, 12, 13, 14])

In [18]:
# This performs element-wise multiplication
x*2

array([2, 4, 6, 8])

In [16]:
# Let's add both arrays 
x + y  # Same as [x[0] + y[0], ... ,x[3] + y[3]]

array([ 6,  8, 10, 12])

In [19]:
# Let's multipy both arrays 
x * y # Same as [x[0] * y[0], ... ,x[3] * y[3]]

array([ 5, 12, 21, 32])

In [20]:
# Let's compute a polynomial 
def f(x):
    return 3*x**2 - 2*x + 7

In [21]:
f(x)

array([ 8, 15, 28, 47])

In [57]:
# Let's create a multi-dimensional arrays with NumPy
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
# The result is a 3 by 4 array
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
# This selects row 1, column 2
a[1,2]

7

In [59]:
# This selects row 1.
# Note Python is zero based indexing
a[1]

array([5, 6, 7, 8])

In [60]:
# This selects column 2
a[:, 2]

array([ 3,  7, 11])

In [61]:
# This will select rows 1 to but not including 3 and 
# columns 1 to but not including 3
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [62]:
# This will select a subregion of a and change it
a[1:3, 1:3] += 10
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [63]:
# This will select everything from row 1 onward
a[1:]

array([[ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [64]:
# This will select everything up to row 1
a[:1]

array([[1, 2, 3, 4]])

In [65]:
# This will skip every other row 
a[::2]

array([[ 1,  2,  3,  4],
       [ 9, 20, 21, 12]])

In [66]:
# This will select all the rows and columns from 1 onward
a[:,1:]

array([[ 2,  3,  4],
       [16, 17,  8],
       [20, 21, 12]])

In [139]:
# NumPy also has a matrix object that follows linear algebra rules. 
m = np.matrix([[1,-2, 3],
               [0, 4, 5],
               [7, 8,-9]])
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [140]:
# We can transpose m
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

### Shapes, dimensions, and axis. 

In NumPy each dimension is called an *axis*. The total number of dimensions(or axis) of an array is called it's *rank*. In the example above b is a 3 by 3 array and therefore it's rank 2. An array's tuple of axis lengths is called the *shape* of the array.

Note: this definition is different than linear algebra since a 3 by 3 matrix can have a rank of 3. 

In [141]:
b = np.array([[ 4, 5, 6], 
              [ 7, 8, 9], 
              [10,11,12]])
b

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [142]:
# Let's look at the shape of b 
b.shape

(3, 3)

In [143]:
# The number of dimensions or "rank" of b
b.ndim

2

In [144]:
# The size is the total number of elements of b
b.size

9

In [145]:
# This will give you the length of axis 0 or # of rows
len(b)

3

For 3 dimensional arrays, the depth dimension must be specified first in NumPy. Let's look at an example on why this is the case.

In [158]:
k = np.zeros((2,3,4))
k

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [159]:
# Let's define a Python list (3 brackets deep)
l = [[[0., 0., 0., 0.],
      [0., 0., 0., 0.],
      [0., 0., 0., 0.]],
     
     [[0., 0., 0., 0.],
      [0., 0., 0., 0.],
      [0., 0., 0., 0.]]
    ]
l

[[[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]],
 [[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]]

Above we get the first level of `l` has exactly 2 elements (just as the first dim on `k` which is 2 rows). 

Each of these in itself is a list with 3 elements, which is the second dim of `k` (3 columns).

The lists that are the most deeply nested have 4 elements each, same as the third dim of `k`. 

This is essentially can be thought of a 4 stacked arrays of 2 rows and columns.

### Common functions

When using a Jupyter Notebook we can always look at the header for a specific method by highlighting it and then pressing the hotkeys:

`Shift + Tab`

In [75]:
# Let's set a to a 3 by 4 array of zeros
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
# Let's set a to a 3 by 4 array of ones 
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
# Let's set a to an 12-element array 
# with indices incremeted by
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
# Let's set a to an array that evenly distributed between
# a max and min value with a specified size
a = np.linspace(0,5/3, 6)
# linspace(min, max, size)
a

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [80]:
# Let's set r to a normally distributed 3 by 4 matrix
r = np.random.randn(3,4)
r

array([[ 0.43172945, -0.17629425,  0.06483866, -1.2012376 ],
       [ 0.50343819, -0.4381214 ,  2.16523893,  1.44145005],
       [ 1.20850245,  1.88568781,  0.73138613,  0.58734712]])

In [81]:
# Let's set r to a uniformally distributed 3 by 4 matrix
r = np.random.rand(3,4)
r

array([[0.40608926, 0.2437063 , 0.18260629, 0.11467866],
       [0.36886164, 0.11921327, 0.38275333, 0.37289571],
       [0.17970467, 0.27870242, 0.41956284, 0.23052329]])

In [82]:
# Let's create a function mapping and assingn to an
# array with a shape of our choice

# Let's first define the function
def my_function(z,y,x):
    return x*y + z

# Let's use fromfunction to create a mapping 
# from my_function to a result that creates a
# 3 by 2 by 10 array that depends on the x,y,z 
# coordinates of the array
a = np.fromfunction(my_function, (3,2,10))
a

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

       [[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]])

The above output is 3 by 2 by 10. Meaning 2 is the number of rows, 10 is the number of columns, and 3 is the depth of the array. The depth axis is always first in numpy for 3-dim arrays. 

In [138]:
# We can also set the shape of an array
g = np.arange(24)
print(g)
print('Rank', g.ndim)
print('\n')
g.shape = (2,3,4)
print(g)
print('Rank',g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank 1


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank 3


In [92]:
# We can create a 1-dimensional 'view' of the array g
g.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [93]:
# We can create a 1-dimensional 'copy' of the array g
g.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

`reshape()` is almost exactly like reshape in MatLab.
The reshape function returns a new ndarray object pointing to the same data. 

In [105]:
# Below is similar to range in Matlab
c = np.arange(6)
# The result should be an array of length 6 
# Incremented by 1 and starting from 0
c

array([0, 1, 2, 3, 4, 5])

In [106]:
# Let's reshape the above 1 by 6 array into a 3 by 2
c.reshape(3,2) # Note this is in-place, return is void
c

array([0, 1, 2, 3, 4, 5])

In [107]:
# Need to assign c.reshape()
c = c.reshape(3,2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [108]:
# If we put a -1 as the arg then it will infer the size 
# of that dim from the other dim
c = c.reshape(-1,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [109]:
# Again
c = c.reshape(3, -1)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [110]:
# Let's transpose c
c = c.transpose()
c

array([[0, 2, 4],
       [1, 3, 5]])

In [116]:
# np.r_ concatenates along the first dimension
np.r_[c.flatten(), 0, 0, c.flatten()]

array([0, 2, 4, 1, 3, 5, 0, 0, 0, 2, 4, 1, 3, 5])

In [119]:
c

array([[0, 2, 4],
       [1, 3, 5]])

In [120]:
# np.c_ concatenates along the second dimension
np.c_[c.flatten(), np.zeros(6), np.zeros(6), c.flatten()]

array([[0., 0., 0., 0.],
       [2., 0., 0., 2.],
       [4., 0., 0., 4.],
       [1., 0., 0., 1.],
       [3., 0., 0., 3.],
       [5., 0., 0., 5.]])

In [135]:
# meshgrid is useful for evaluating functions on a grid
x = np.arange(-5, 5, .1)
y = np.arange(-5, 5, .1)
xx, yy = np.meshgrid(x, y, sparse=True)
print('xx size is',xx.size,'; yy size is',yy.size)
z = np.sin(xx**2 + yy**2) / (xx**2 + yy**2)

xx size is 100 ; yy size is 100


In [140]:
# NaN
x = np.array([[1.,2.], [np.nan, 3.],[np.nan,np.nan]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [141]:
# Filter out use isnan()
x[~np.isnan(x)]

array([1., 2., 3.])

In [144]:
# Split arrays
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [145]:
# Let's split the array horizontally about the second axis
np.hsplit(x, 2)

[array([[[0., 1.]],
 
        [[4., 5.]]]), array([[[2., 3.]],
 
        [[6., 7.]]])]

In [146]:
# Let's split vertically about the second axis
np.vsplit(x, 2)

[array([[[0., 1.],
         [2., 3.]]]), array([[[4., 5.],
         [6., 7.]]])]

In [147]:
# We also use this which will split the array into
# a array with subarray of equal size 
np.array_split(x, 3)

[array([[[0., 1.],
         [2., 3.]]]), array([[[4., 5.],
         [6., 7.]]]), array([], shape=(0, 2, 2), dtype=float64)]

### Universal Functions

On ndarrays universal functions can accept an axis as an optional argument. 


In [24]:
# We can combine method calls using the dot notation
position = np.arange(4).reshape(2,2)
position

array([[0, 1],
       [2, 3]])

We will see a lot of assignments like shown above where the first call (after the first dot) creates a 4 element NumPy array (or an array of some shape) and then a second call (after the second dot) where we call  a function that does something to the array. Here we are changing the shape of the array.

In [25]:
# The universal function sum can have an axis as an arg
position.sum(axis = 0) # sum across the rows

array([2, 4])

In [27]:
position.sum(axis = 1) # sum across columns

array([1, 5])

Universal functions can also take the form `ufunc.outer(A,B)` where the ufunc operation will be applied to all pairs (a,b) with a in A and b in B (because of `outer`). 

For more information on the universal functions that exist in NumPy please visit

https://docs.scipy.org/doc/numpy-1.15.0/reference/ufuncs.htmlm

In [30]:
# This is all our positions along x axis
position[:,0]

array([0, 2])

In [32]:
# This is all our positions along the y axis
position[:,1]

array([1, 3])

In [34]:
# The universal function is subtract here applied to (A,B)
# np.subtract.outer([a1, a2], [b1, b2])
# The return we get is     [[a1-b1, a1-b2]
#                           [a2-b1, a2-b2]]
dx = np.subtract.outer(position[:,0], position[:,0])
print(dx)
dy = np.subtract.outer(position[:,1], position[:,1])
print(dy)

[[ 0 -2]
 [ 2  0]]
[[ 0 -2]
 [ 2  0]]


In [35]:
# Let's find the distance
distance = np.hypot(dx, dy)
distance

array([[0.        , 2.82842712],
       [2.82842712, 0.        ]])

In [44]:
print(position)
position*position

[[0 1]
 [2 3]]


array([[0, 1],
       [4, 9]])

In [45]:
# Let's normalize the position
norm = np.sqrt(position*position).sum(axis=1).reshape(len(position))
norm

array([1., 5.])

### Iterating 

Before going over iterating over ndarrays let's quickly review `for` loops in Python. 

The `range()` function in Python is a built-in function used to generate a sequence of numbers over time. At its simplest, it accepts an integer and returns a range object (a type of iterable). If in line with a `for` statement then the `range()` function is evaluated just before the first iteration of the loop and no reevaluated. It just keeps track of the last number and the step size to provide a flow of numbers.

In [74]:
# This returns a range object called a "iterable" in Python
# Which is a handy way of storing large data that
# are ready to be iterated over. 
i = range(4)
i

range(0, 4)

In [75]:
# What is the above range
# We can see what it is by changing it to a list object
list(i)

[0, 1, 2, 3]

In [72]:
# We can see that changing the value of x inside the loop 
# does not affect the number of iterations
x = 4
for i in range(x):
    print(i)
    x = 5

0
1
2
3


Note that above the `i` that is used in the `for` loop can be thought of a variable that will be bound to each element in the sequence (or get the same location in memory that is occupied by the element in the sequence) resulting from `range()`. We can then use `i` to continuously perform operations. 

In [76]:
# The outer loop range is evaluated only once. 
# The inner loop is evaluated each time the inner for
# statement is reached. 
x = 4
for j in range(x):
    for i in range(x):
        print(i)
        x = 2

0
1
2
3
0
1
0
1
0
1


Let's now start iterating over arrays. 

In [46]:
# Let's first create a rank 3 NumPy array
c = np.arange(24).reshape(2,3,4) 
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [69]:
# Let's iterate over the multi-dim array
count = 0
for m in c:
    count += 1
    print('Output for (' + str(count) + ', 3, 4) ')
    print(m)

Output for (1, 3, 4) 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Output for (2, 3, 4) 
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [68]:
# Note that len(c) == c.shape[0]
len(c) == c.shape[0]

True

In [71]:
for l in range(len(c)):
    print('Output for (' + str(l) + ', 3, 4) ')
    print(c[l])

Output for (0, 3, 4) 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Output for (1, 3, 4) 
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [78]:
# print out all elements of the ndarray we first need to 
# flatten the array 
for l in c.flat:
    print("Output:", l)

Output: 0
Output: 1
Output: 2
Output: 3
Output: 4
Output: 5
Output: 6
Output: 7
Output: 8
Output: 9
Output: 10
Output: 11
Output: 12
Output: 13
Output: 14
Output: 15
Output: 16
Output: 17
Output: 18
Output: 19
Output: 20
Output: 21
Output: 22
Output: 23


### Stacking arrays

We can also stack (concatenate) arrays in NumPy. 

In [79]:
# Using full(shape, fill_value) wlll create an array 
# with the given shape and fill_value
q1 = np.full((3,4), 1.0)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
q2 = np.full((4,4), 2.0)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [83]:
# Let's stack the array vertically 
# The number of columns of both the arrays must be equal
q3 = np.vstack([q1, q2])
q3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [84]:
# We can also do a horizontal stack
# The number of rows must be equal
q4 = np.hstack([q3, q3])
q4

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2.]])

In [85]:
# The concatenate function can work along any existing axis
q5 = np.concatenate([q1, q2], axis=0)
q5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [87]:
# The stack function will stack along a new axis
# The array has to be the same shape
q6 = np.stack([q3, q5])
q6

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

### Memory and Datatypes
*dtype* describes a single item in the array

 - type **scalar type** of the data one of:
   int8 to float64
   str, unicode, void (flexible size)
 - itemsize **size** of data block
 - byteorder big-endian is >| , little-endian is <|, native to system is =, and not applicable is |

In [104]:
# We can specify the type of any array with dtype
d = np.array([1, 2, 3, 4], dtype = np.float)
d

array([1., 2., 3., 4.])

In [105]:
# Let's check the type of the array
d.dtype

dtype('float64')

In [100]:
# Let's check the number of bytes 
d.itemsize

8

In [101]:
# Let's check the memory location
d.data

In [102]:
# Let's check the binary representation 
bytes(d.data)

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@'

In [103]:
# Let's check the byteorder
d.dtype.byteorder

'='

In [92]:
# Let's cast the above array to an integer of 1 byte
d =  d.astype(np.int8)

In [93]:
# Let's check the number of bytes
d.itemsize

1

In [94]:
# Let's check the memory location
d.data

In [95]:
# Let's check the binary rep
bytes(d.data)

b'\x01\x02\x03\x04'

### Strides
Let's look at the way in which NumPy performs indexing. 

In [169]:
x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]], dtype = np.int8)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [170]:
bytes(x.data)

b'\x01\x02\x03\x04\x05\x06\x07\x08\t'

A which byte above does the item `x[1,2]` begin?

To answer this we must consider **strides**. Strides are the number of bytes to jump to find the next element in data. In Python there is 1 stride per jump per dimension. 

In [146]:
# Let's look at the strides for x
x.strides

(3, 1)

In above cell results in the tuple `(3,1)`. Here 3 corresponds to the number of bytes that must be moved in the first dimension (along the rows). The second element 1 corresponds to the number of bytes to jump in the second dimension. 

In [148]:
# Let's use the the above information to find x[1,2]
# Jump 1 step along the first dim and jump 2 along second
byte_offset = 3*1 + 1*2
# Flatten x
x.flat[byte_offset]

6

In [149]:
x[1, 2]

6

In [150]:
x = np.array([[1, 2, 3],
              [4, 5, 6]], dtype = np.int16)
# Each integer is 2 bytes or 16 bits
x.strides 

(6, 2)

In [151]:
bytes(x.data)

b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'

Python (and C) follows *row-major* ordering of data. 

Matlab (and Fortran) follow *column-major* ordering. 

  <img src='images/row_and_column_major_order.png'>
 
Here we show the order of data access depending on if the programming language follows row-major ordering (left column below) or column-major ordering (right column below).

$$
  A=
  \left[ {\begin{array}{ccc}
   a_{11} & a_{12} & a_{13}\\
   a_{21} & a_{22} & a_{23}\\
   a_{31} & a_{32} & a_{33}\\
  \end{array} } \right]
   \rightarrow
   \left[ {\begin{array}{ccc}
   A[0, 0] & A[0, 1] & A[0, 2]\\
   A[1, 0] & A[1, 1] & A[1, 2]\\
   A[2, 0] & A[2, 1] & A[2, 2]\\
  \end{array} } \right]
$$

|Address | Access | Value  ||Address | Access | Value  | 
|--------|--------|--------||--------|--------|--------|
|    0   | A[0, 0]|$a_{11}$||    0   | A[0, 0]|$a_{11}$|
|    1   | A[0, 1]|$a_{12}$||    1   | A[1, 0]|$a_{21}$|
|    2   | A[0, 2]|$a_{13}$||    2   | A[2, 0]|$a_{31}$|
|    3   | A[1, 0]|$a_{21}$||    3   | A[0, 1]|$a_{12}$|
|    4   | A[1, 1]|$a_{22}$||    4   | A[1, 1]|$a_{22}$|
|    5   | A[1, 2]|$a_{23}$||    5   | A[2, 1]|$a_{32}$|
|    6   | A[2, 0]|$a_{31}$||    6   | A[0, 2]|$a_{13}$|
|    7   | A[2, 1]|$a_{32}$||    7   | A[1, 2]|$a_{23}$|
|    8   | A[2, 2]|$a_{33}$||    8   | A[2, 2]|$a_{33}$|


The memory layout can affect performance.

In [153]:
x = np.zeros((2000, ))
# Let's skip every 67 elements
y = np.zeros((2000*67, ))[::67]
# The shape of x and y are the same
x.shape, y.shape

((2000,), (2000,))

In [154]:
# Let's time summing over the array x
%timeit x.sum()

2.45 µs ± 518 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [155]:
# Let's time summing over the array y
%timeit y.sum()

4.21 µs ± 317 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [157]:
x.strides, y.strides

((8,), (536,))

As we can see, array y has a larger stride. The CPU pulls data from main memory to the cache in blocks of contiguous memory. If many arrays are consecutively operated to fit on a single memory block (smaller stride) then fewer transfers are needed and the computation is faster. 

### Memory layout

In general, the contiguous block of memory can be accessed using an indexing scheme. Such an indexing scheme is defined by *shape* and *data type*. This is what you define for a new array.

In [161]:
# Let's use shape and dtype to define a new array
z = np.arange(9).reshape(3,3).astype(np.int16)
# Let's get the shape
z.shape

(3, 3)

In [167]:
# Let's get the number of dims
z.ndim

2

In [159]:
# Let's get the item size
z.itemsize

2

In [162]:
# Let's compute the strides 
strides = z.shape[1]*z.itemsize, z.itemsize
strides

(6, 2)

In [163]:
# Let's verify
z.strides

(6, 2)

In [166]:
# We can find the start and end byte offsets of a specific
# index using strides
offset_start = 0
index = (1,1)
for i in range(z.ndim):
    offset_start += strides[i] * index[i]
offset_end = offset_start + z.itemsize
print('Start offset is', offset_start, '\n', 'End offset is', offset_end)

Start offset is 8 
 End offset is 10


The memory layout for z is shown below.

### Views and copies of data

*Views* and *copies* of data can be used for optimization of numerical computations. First, let's distinguish between *basic indexing* and *fancy indexing*. Basic indexing or just indexing will return a view while fancy indexing will return a copy of the data. This difference is important because the base array is modified in indexing whereas the base array is not modified in fancy indexing.  

Let's look at examples below. 

First, let's consider what we mean by basic indexing, views, and changing the base array with the example below. 

In [181]:
z = np.zeros(9)
print('The base array for z is', z)
# Lets's create a view of data using basic indexing
z_view = z[:3] 
# The ellipsis below means for all indices
z_view[...] = 1
print('The base array for z is now', z) # changes base 

The base array for z is [0. 0. 0. 0. 0. 0. 0. 0. 0.]
The base array for z is now [1. 1. 1. 0. 0. 0. 0. 0. 0.]


Second, let's consider what we mean by fancy indexing, copies, and not changing the base array with the example below.

In [180]:
# Let's set z back to original array
z = np.zeros(9)
print('The base array for z is', z)
#Let's create a copy of data using fancy indexing
z_copy = z[[0, 1, 2]]
z_copy[...] = 1
print('The base array for z is now', z) # doesn't change base 

The base array for z is [0. 0. 0. 0. 0. 0. 0. 0. 0.]
The base array for z is now [0. 0. 0. 0. 0. 0. 0. 0. 0.]


If you use fancy indexing it's better to keep a copy of your fancy index and work with it as shown below.

In [182]:
z = np.zeros(9)
# Let's make a copy of our fancy index
index = [0, 1, 2]
z[index] = 1
print(z)

[1. 1. 1. 0. 0. 0. 0. 0. 0.]


If you don't know whether you're indexing is creating a view or copy of the data then you can check the base data. If the result is `None` then the result is a copy as shown below. 

In [186]:
# arg1 = start, arg2 = end, arg3 = shape 
z = np.random.uniform(0, 1, (5,5))
print('z = \n', z)
# create a view of z, take up to row 3 and all columns
z1 = z[:3, :]
# create a copy of z, take rows 1, 2, 3 and all columns
z2 = z[[0, 1, 2], :]
# allclose(a, b) returns true if all elements of a and b
# are equal within a tolerance
np.allclose(z1, z2)

z = 
 [[0.07044807 0.40267768 0.53826605 0.10275411 0.11239758]
 [0.1496346  0.7069368  0.26483219 0.8475687  0.95261254]
 [0.87768467 0.03034713 0.30686387 0.83845492 0.67201406]
 [0.4187745  0.11383059 0.91553949 0.10420176 0.70397835]
 [0.92877527 0.60539578 0.05725155 0.81402303 0.52538476]]


True

In [189]:
# Let's now check the base of z1 and z2
print('z1 base is z is', z1.base is z)
print('z2 base is z is', z2.base is z)
print('z2 base is None is', z2.base is None)

z1 base is z is True
z2 base is z is False
z2 base is None is True


Some NumPy functions like `ravel` return a view when possible while others like ` flatten` will return a copy. 

In [198]:
z = np.zeros((5,5))
# Below we will get a view
print(z.ravel().base is z)
# Below we will get a copy since we are skipping
print(z[::2, ::2].ravel().base is z)
# Below we will get a copy 
print(z.flatten().base is z)

True
False
False


We can also use structural indexing tools. One such is `np.newaxis` object that can be used within array indices to add a new dimension of size 1, creating a view of the original data. 

In [71]:
y = np.arange(35).reshape(5,7)
y.shape

(5, 7)

In [72]:
# This will create a view of the data and add a dim of size 1
y[:, np.newaxis,:].shape

(5, 1, 7)

In [73]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [74]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [75]:
x[np.newaxis, :]

array([[0, 1, 2, 3, 4]])

In [76]:
# This will broadcast
x[:, np.newaxis] + x[np.newaxis, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### Temporary copies

Copies can be made explicitly like before but the most general case is the implicit creation of intermediate copies. This is the case when you doing some arithmetic with arrays. Let's look at examples. 

In [201]:
x = np.ones(10, dtype = np.int)
y = np.ones(10, dtype = np.int)
# Below we are creating intermediate copies
# There is one copy that is created for 2*x and one for 2*y
# There is another copy for 2*x + 2*y
A = 2*x + 2*y
A

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In the above example intermediate arrays have been created but if these array are large then you must be careful. If you don't need x and y after then an alternative solution is below.

In [200]:
x = np.ones(10, dtype = np.int)
y = np.ones(10, dtype = np.int)
np.multiply(x, 2, out = x)
np.multiply(y, 2, out = y)
np.add(x, y, out = x)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

Using the above solution no temporary array ahs been created. There are cases where copies need to be created. Let's look at a couple of performance test. 

In [20]:
# Let's look at performance
x = np.ones(10000000, dtype = np.int)
y = np.ones(10000000, dtype = np.int)
z = np.zeros(10000000, dtype=np.int)

In [21]:
# Here a temporary array has been created
%timeit z = x + y

21.4 ms ± 1.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
# Here a temporary array has not been created
%timeit np.add(x, y, out = z)

14.9 ms ± 237 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Finally, if we're given two arrays z1 and z2 we would like to know if z2 is a view of z1. If yes, what is the view?

In [23]:
z1 = np.arange(10)
# z1[start:stop:step], -1 means the last indice
z2 = z1[1:-1:2]

In [24]:
# Let's check if it's a view
print(z2.base is z1)

True


Since z2 is a view of z1  it can be expressed as `z2 = z1[start:stop:step]`. For step we can use the strides property of any array that gives the number of bytes that go from one element to the next. Because both arrays are only 1 dimenisonal we can compare the first stride.  

In [25]:
# // means floor division
step = z2.strides[0] // z1.strides[0]
print(step)

2


To find the start and stop indices we can take advantage of `byte_bounds` method that returns a pointer to the end-points of an array:

In [30]:
# Following the above diagram, we want to know the 
# starting offset from z1 for z2
offset_start = np.byte_bounds(z2)[0] - np.byte_bounds(z1)[0]
print('Start byte offset for z2 is', offset_start)

# Following the above diagram, qwe want to know the 
# stop offset from z1 for z2
offset_stop = np.byte_bounds(z2)[-1] - np.byte_bounds(z1)[-1]
print('Stop byte offset for z2 is', offset_stop)

Start byte offset for z2 is 8
Stop byte offset for z2 is -16


Converting the byte offset to indices is straightforward using `itemsize`:

In [36]:
start = offset_start // z1.itemsize
# Note the offset_stop is negative so need the size of z1
stop = z1.size + offset_stop // z1.itemsize
print('(start =',start,',','stop =', stop,',','step =', step,')')

(start = 1 , stop = 8 , step = 2 )


In [37]:
# Let's check the results
print(np.allclose(z1[start:stop:step], z2))

True


### Broadcasting 

Refers to how Numpy treats arrays with different shapes during arithmetic operatons. In general, the smaller array is broadcasted to the larger array. Broadcasting usually leads to efficient algorithm implementation since there isn't a need for needless copies of data. Broadcasting can also lead to inefficient implementations as well. The rules are stated below. 

Start with trailing dimensions and work forward. The two dimensions are compatible if: 

1) they are equal 

2) one of them is 1. 

When either of the dimension compared is 1 the other is used, dim with size 1 are stretched or "copied" to match.

More information about broadcasting in NumPy can be found here:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

Here are some examples. Note we have aligned the trailing dim:

Here are examples of shapes that don't broadcast:

In [116]:
# Let's look at an example
x = np.arange(4)
print(' x = \n', x)
print('The shape of x is', x.shape)
print('\n')

xx = x.reshape(4,1)
print(' xx = \n', xx)
print('The shape of xx is', xx.shape)
print('\n')

y = np.ones(5)
print('y = \n', y)
print('The shape of y is', y.shape)
print('\n')

 x = 
 [0 1 2 3]
The shape of x is (4,)


 xx = 
 [[0]
 [1]
 [2]
 [3]]
The shape of xx is (4, 1)


y = 
 [1. 1. 1. 1. 1.]
The shape of y is (5,)




In [109]:
# This will not work since the trailing dims are
# x (1d array): 4
# y (1d array): 5
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [110]:
# This will work since 
#     xx (2d array): 4 x 1
#      y (1d array):     5
# Result (2d array): 4 x 5
result = xx+y
print(result)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [119]:
# More examples
h = np.arange(5).reshape(1,1,5)
h

array([[[0, 1, 2, 3, 4]]])

In [120]:
#      h (3d array): 1 x 1 x 5
#        (1d array):         5
# Result (3d array): 1 x 1 x 5
# Same as h + [[[10, 20, 30, 40, 50]]]
h + [10, 20, 30, 40, 50]

array([[[10, 21, 32, 43, 54]]])

In [121]:
k = np.arange(6).reshape(2, 3)
k

array([[0, 1, 2],
       [3, 4, 5]])

In [122]:
#      k (2d array): 2 x 3
#        (2d array): 2 x 1      
# Result (2d array): 2 x 3
# Same as k + [[100, 100, 100], [200, 200, 200]]
k + [[100], [200]]

array([[100, 101, 102],
       [203, 204, 205]])

In [123]:
#      k (2d array): 2 x 3
#        (1d array):     3      
# Result (2d array): 2 x 3
# Same as k + [[100, 200, 300], [100, 200, 300]]
k + [100, 200, 300]

array([[100, 201, 302],
       [103, 204, 305]])

In [124]:
# Same as k + [[1000, 1000, 1000], [1000, 1000, 1000]]
k + 1000

array([[1000, 1001, 1002],
       [1003, 1004, 1005]])

### Logical Indexing

We can use masks and boolean indexes.

In [44]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [46]:
# The elements are iterated and returned in row-major
# order. The result is a copy of the data not a view as
# with slices.
b = y > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [47]:
y[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [49]:
print(y[b[:, 5]])
print('\n')
print(y[[False, False, False, True, True]])

[[21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


[[21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


As shown in the example above if the boolean array, b, has fewer dimensions than the array that is being indexed then this is equivalent to `y[b,:,:,...]` where y is indxed by b followed by as many `:` are needed to fill out the shape of y. Above example is `y[b,:]`.

### More Fancy Indexing

Let's look at more examples of fancy (or advanced) indexing. 

In [53]:
# Let's create a random array
# Set the seed state to 42
rand = np.random.RandomState(42)
x = rand.randint(100, size = 10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [40]:
# This will return a Python list
[x[3], x[7], x[2]]

[71, 86, 14]

In [41]:
# Let's use fancy indexing to return an array copy
ind = [3, 7, 2]
x[ind]

array([71, 86, 14])

When using fancy indexing the shape of the result will reflect the shape of the index arrays rather than the array being indexed. 

In [43]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [78]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
# This is the same as x[1,1]
x[(1,1)]

5

In [51]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
# This is the same as returning x[0,2], x[1,1], x[2,3]
x[row,col]

array([ 2,  5, 11])

Let's combine basic indexing (using slices) and fancy indexing (using arrays). 

In [58]:
# Here we get a copy
# Is the same as x[1,1], x[1,2]
x[1:2, [1,2]]

array([[5, 6]])

In [88]:
z = np.arange(27).reshape(3,3,3)
# Below is the same as z[1, :, :, 2]
z[1,...,2]

array([11, 14, 17])

In general it is preferable to use slicing or basic for indexing. More information about NumPy indexing can be found here
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

Some more examples.

In [99]:
# Let'se select all the rows that sum up to less than equal
# to a certain value
x = np.array([[0, 1],
              [1, 1],
              [2, 2]])
# Let's sum along the last dimension
rowsum = x.sum(-1)

In [103]:
rowsum <= 2

array([ True,  True, False])

In [102]:
x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

In [170]:
# We can change a row vector to a 2 dim column vector 
# using None  
ymin, ymax, yn = -1.25, 1.25, int(25/3)
y = np.linspace(ymin, ymax, yn, dtype = np.float)
print(y)
print(y.shape)

[-1.25       -0.89285714 -0.53571429 -0.17857143  0.17857143  0.53571429
  0.89285714  1.25      ]
(8,)


In [171]:
y = y[:, None]
print(y)
print(y.shape)

[[-1.25      ]
 [-0.89285714]
 [-0.53571429]
 [-0.17857143]
 [ 0.17857143]
 [ 0.53571429]
 [ 0.89285714]
 [ 1.25      ]]
(8, 1)


Finally, this is a good NumPy cheat sheet:

<img src="images/numpy_cheat_sheet.jpg">

To view the a bigger version go to:
https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

### NumPy for Code Vectorization

Let's look at using NumPy for vectorizing code and see the performance benefits. Let's start with a program that simulates a random walk. 

Object-Oriented Approach:

In [173]:
import random

class RandomWalker:
    def __init__(self):
        self.position = 0
        
    def walk(self, n):
        self.position = 0
        for i in range(n):
            yield self.position
            self.position += 2*random.randint(0,1) - 1

In [174]:
%%timeit
walker = RandomWalker()
walk = [position for position in walker.walk(1000)]

1.37 ms ± 11.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Procedural Approach:

In [177]:
def random_walk(n):
    position = 0
    walk = [position]
    for i in range(n):
        position += 2*random.randint(0,1) - 1
        walk.append(position)
    return walk

In [178]:
%timeit walk=random_walk(1000)

1.26 ms ± 31.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


The procedural approach saves a few cycles but is not much more efficient. 

Here we are using the Python *itertools*, which is a set of functions in Python for creating iterators for efficient looping.

For more information go to: 
https://docs.python.org/3/library/itertools.html

In [180]:
# Let's use Python itertool called accumulate
from itertools import accumulate

# This example returns a iterator that is the same as
# a[0], a[0] + a[1], a[0] + a[1] + a[2], [0] + a[1] + a[2] + a[3]
accumulate([1, 2, 3, 4])

In [181]:
# We can use list object to return a list
list(accumulate([1, 2, 3, 4]))

[1, 3, 6, 10]

In [184]:
# Let's try writing the random_walk function by first 
# generating all the steps and accumulate them without
# any loops

def random_walk_faster(n = 1000):
    from itertools import accumulate
    steps = random.choices([-1, +1], k = n)
    return [0] + list(accumulate(steps))

In [186]:
%timeit random_walk_faster(1000)

245 µs ± 34.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Above we have vectorized our function, instead of looping for picking sequential steps and add them to the current position we first generated all the steps at once and use the `accumulate` function to compute all the positions.

Now let's use the power of NumPy vectorization!

In [187]:
def random_walk_fastest(n=1000):
    steps = np.random.choice([-1, +1], n)
    return np.cumsum(steps)

In [189]:
%timeit walk = random_walk_fastest(1000)

21.1 µs ± 4.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Wow! That was about a 10x speed improvement! 

With NumPy the readibility of the code may suffer and so it's important to comment the code.

Some more NumPy vectorization.

Sometimes a problem is inherently vectorizable and requires only a few tricks to make it faster. 

In [192]:
def add_python(z1, z2):
    # Here zip(z1, z2) creates an iterator of tuples 
    #for corresponding elements in both arrays or
    # (z1[0], z2[0]), (z1[1], z2[1]), (z1[2], z2[2]), ...
    return [z1 + z2 for (z1, z2) in zip (z1, z2)]

In [193]:
# Vectorized version using NumPy
def add_numpy(z1, z2):
    return np.add(z1, z2)

### Typical NumPy patterns for Machine Learning

A lot of the time we would like to split data into training, testing, and validation sets. This can require a lot of time and is a part of data preparation. Much of this work is performed using tools like NumPy and Pandas (Pandas will be the topic of a future notebook) and before using a Machine Learning framework like Tensorflow. Below are some examples of common patterns for preparing data. 

Let's look at some of the things we can do to ensure that we are performing cross-validation. Let's do this for the MNIST dataset. 

In [371]:
# Let's use sklearn library to import MNIST data
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original')
mnist

{'DESCR': 'mldata.org dataset: mnist-original',
 'COL_NAMES': ['label', 'data'],
 'target': array([0., 0., 0., ..., 9., 9., 9.]),
 'data': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)}

In [372]:
# Note that DESCR is the the key describing the dataset 
# The 'data' key containing an array 
# with one row per instance and one column per feature
# The 'target' key has an array with labels 

X, y = mnist["data"], mnist["target"]

A lot of the time we want to put a test set aside before inspecting the data. MNIST luckily is already split inot a training set (first 60,000) and a test set (last 10,000).

In [373]:
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[600000:]

Now we want to ensure that the cross-validation folds are similar. We can do this by shuffling the data.

In [374]:
# Let's create a random NumPy array that that is (6000,)
shuffle_index = np.random.permutation(60000)
# Let's shuffle the training set using our shuffle index
X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]

We can use the above dataset to create a  binary classifier to classify particular digits. 